import React, { useMemo, useState } from 'react'

const tabs = ['STRATEGY', 'TELEMETRY', 'ENERGY', 'OVERTAKE', 'LEGENDS']
const strategies = {
  ATTACK: { color: '#ff7043', cost: '2.4 MJ', chance: '72%', text: 'Spend energy now while the closing rate is strong.' },
  SAVE: { color: '#63e6be', cost: '0.0 MJ', chance: '18%', text: 'Protect the reserve and keep the position stable.' },
  DELAY: { color: '#a9bfff', cost: '1.5 MJ', chance: '81%', text: 'Wait for the next braking zone with better energy value.' },
}

function Chart({ type = 'speed', focus }) {
  const width = 760; const height = 205; const pad = { x: 42, y: 20, r: 20, b: 30 }
  const values = useMemo(() => Array.from({ length: 48 }, (_, i) => {
    const x = i / 47
    if (type === 'gap') return 1.65 - x * 1.08 + Math.sin(i * .42) * .08
    if (type === 'throttle') return Math.max(4, Math.min(100, 52 + Math.sin(i * .3) * 42 + (i > 30 ? 12 : 0)))
    if (type === 'brake') return Math.max(0, Math.min(100, i > 13 && i < 20 ? 82 - Math.abs(16 - i) * 11 : i > 36 && i < 41 ? 71 - Math.abs(38 - i) * 15 : 2))
    return 218 + Math.sin(i * .24) * 27 + (i > 26 ? 16 : 0) - (i > 38 ? 32 : 0)
  }), [type])
  const compare = values.map((v, i) => type === 'gap' ? v + .12 + Math.sin(i * .45) * .05 : v - 12 + Math.sin(i * .34) * 5)
  const min = type === 'gap' ? 0 : 0; const max = type === 'gap' ? 2 : type === 'speed' ? 290 : 100
  const point = (v, i) => `${pad.x + i / 47 * (width - pad.x - pad.r)},${pad.y + (1 - (v - min) / (max - min)) * (height - pad.y - pad.b)}`
  const primary = values.map(point).join(' '); const secondary = compare.map(point).join(' ')
  const markerX = pad.x + focus / 47 * (width - pad.x - pad.r)
  return <div className="ov-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${type} comparison chart`}><g className="chart-grid"><line x1={pad.x} y1={pad.y} x2={width - pad.r} y2={pad.y} /><line x1={pad.x} y1={(height - pad.b) / 2} x2={width - pad.r} y2={(height - pad.b) / 2} /><line x1={pad.x} y1={height - pad.b} x2={width - pad.r} y2={height - pad.b} /></g><polyline className="chart-secondary" points={secondary} /><polyline className="chart-primary" points={primary} /><line className="chart-marker" x1={markerX} y1={pad.y} x2={markerX} y2={height - pad.b} /><circle className="chart-marker-dot" cx={markerX} cy={pad.y + (1 - (values[focus] - min) / (max - min)) * (height - pad.y - pad.b)} r="5" /></svg><div className="chart-axis"><span>{type === 'gap' ? '2.0s' : type === 'speed' ? '290' : '100%'}</span><span>{type === 'gap' ? '1.0s' : type === 'speed' ? '220' : '50%'}</span><span>0</span><b>DISTANCE / 5,412 m</b></div><div className="chart-legend"><span><i className="line-real" /> SELECTED DRIVER</span><span><i className="line-reference" /> CAR AHEAD / REFERENCE</span><em>● FOCUS {Math.round(focus / 47 * 100)}%</em></div></div>
}

function DataBadge({ children, tone = 'real' }) { return <span className={`data-badge ${tone}`}><i />{children}</span> }

export function StrategyDashboard() {
  const [tab, setTab] = useState('STRATEGY')
  const [focus, setFocus] = useState(34)
  const [strategy, setStrategy] = useState('DELAY')
  const [drs, setDrs] = useState(true)
  const gap = Math.max(.32, 1.62 - focus * .024)
  const speed = Math.round(218 + Math.sin(focus * .24) * 27 + (focus > 26 ? 16 : 0) - (focus > 38 ? 32 : 0))
  const reserve = Math.round(71 - focus * .32 - (strategy === 'ATTACK' ? 4 : strategy === 'SAVE' ? -2 : 1))
  const feasibility = Math.round(Math.max(19, Math.min(95, 86 - gap * 21 + (drs ? 12 : -16) + (speed > 245 ? 5 : 0))))
  const recommendation = gap < .62 && drs ? 'ATTACK' : gap > 1.1 || !drs ? 'SAVE' : 'DELAY'
  const selected = strategies[strategy]
  return <main className="ov-dashboard">
    <header className="ov-header"><div className="ov-brand"><span>✦</span><strong>OVER<em>VOLT</em></strong><small>RACE STRATEGY INTELLIGENCE</small></div><div className="ov-header-center"><b>2023 LAS VEGAS GRAND PRIX</b><span>RACE / LAP 50 / TURN 14 APPROACH</span></div><div className="ov-header-right"><DataBadge tone="real">CACHED TELEMETRY</DataBadge><button className="ov-menu">☰</button></div></header>
    <section className="ov-toolbar"><div className="ov-select"><span>DRIVER</span><b>PÉREZ</b><i>⌄</i></div><div className="ov-select"><span>OPPONENT</span><b>LECLERC</b><i>⌄</i></div><div className="ov-select"><span>SCENARIO</span><b>LAST-LAP PASS</b><i>⌄</i></div><div className="ov-toolbar-note"><span>DATASET</span><b>FASTF1 / HISTORICAL</b></div></section>
    <nav className="ov-tabs">{tabs.map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}<span className="ov-tab-caveat">One cached scenario · values marked by source</span></nav>
    <section className="ov-content">
      <div className="ov-title-row"><div><p className="ov-eyebrow">SCENARIO ANALYSIS / {tab}</p><h1>Should we spend<br /><em>energy here?</em></h1></div><div className="ov-scenario-summary"><DataBadge tone="real">REAL RACE CONTEXT</DataBadge><strong>PÉREZ <span>vs</span> LECLERC</strong><p>Lap 50 · 5,412 m · Las Vegas</p></div></div>
      {tab === 'STRATEGY' && <>
        <div className="ov-alert"><span>◆</span><div><b>DECISION WINDOW OPEN</b><p>Car ahead is within DRS range. The next braking zone is 1.2 km away.</p></div><strong>{recommendation} RECOMMENDED</strong></div>
        <div className="ov-main-grid"><section className="ov-panel ov-chart-panel"><div className="ov-panel-head"><span>RACE TRACE / SPEED</span><DataBadge tone="real">REAL TELEMETRY</DataBadge></div><Chart type="speed" focus={focus} /><div className="ov-panel-head second"><span>GAP TO CAR AHEAD</span><DataBadge tone="derived">DERIVED</DataBadge></div><Chart type="gap" focus={focus} /></section><aside className="ov-panel ov-energy-panel"><div className="ov-panel-head"><span>ENERGY ENGINE</span><DataBadge tone="simulated">MODELED</DataBadge></div><div className="ov-big-metric"><span>ESTIMATED RESERVE</span><strong>{reserve}<small>%</small></strong><div className="ov-meter"><i style={{ width: `${reserve}%` }} /></div><p>Modeled from braking recovery and throttle expenditure.</p></div><div className="ov-energy-rows"><div><span>RECOVERY OPPORTUNITY</span><b>0.8 MJ</b><em>TURN 14</em></div><div><span>ATTACK COST</span><b>2.4 MJ</b><em>3.2 SEC</em></div><div><span>FUTURE VALUE</span><b>HIGH</b><em>FINAL SECTOR</em></div></div><div className="ov-assumption">SIMULATION ASSUMPTION <p>Regulation constants are versioned model inputs, not team battery measurements.</p></div></aside></div>
        <div className="ov-strategy-row"><div className="ov-section-label"><span>COUNTERFACTUALS</span><b>COMPARE THE CHOICES</b></div><div className="ov-strategy-cards">{Object.entries(strategies).map(([name, data]) => <button key={name} className={`ov-strategy-card ${strategy === name ? 'selected' : ''}`} style={{ '--strategy-color': data.color }} onClick={() => setStrategy(name)}><span>{recommendation === name ? '★ BEST FIT NOW' : 'SCENARIO'}</span><strong>{name}</strong><p>{data.text}</p><div><b>{data.chance}</b><small>PASS CHANCE</small><b>{data.cost}</b><small>ENERGY COST</small></div></button>)}</div></div>
      </>}
      {tab === 'TELEMETRY' && <div className="ov-tab-grid"><section className="ov-panel ov-chart-panel"><div className="ov-panel-head"><span>SPEED COMPARISON</span><DataBadge tone="real">REAL TELEMETRY</DataBadge></div><Chart type="speed" focus={focus} /><div className="ov-panel-head second"><span>THROTTLE APPLICATION</span><DataBadge tone="real">REAL TELEMETRY</DataBadge></div><Chart type="throttle" focus={focus} /></section><section className="ov-panel ov-chart-panel"><div className="ov-panel-head"><span>BRAKE APPLICATION</span><DataBadge tone="real">REAL TELEMETRY</DataBadge></div><Chart type="brake" focus={focus} /><div className="ov-panel-head second"><span>TRACK POSITION</span><DataBadge tone="derived">DERIVED</DataBadge></div><div className="ov-mini-track"><div className="ov-track-line" /><i style={{ left: `${focus / 47 * 100}%` }} /><b>TURN 14</b><span>START</span><span>FINISH</span></div></section></div>}
      {tab === 'ENERGY' && <div className="ov-tab-grid"><section className="ov-panel ov-energy-detail"><div className="ov-panel-head"><span>ENERGY DEPLOYMENT PROFILE</span><DataBadge tone="simulated">MODELED ESTIMATE</DataBadge></div><div className="ov-energy-hero"><strong>{reserve}%</strong><span>ESTIMATED<br />AVAILABLE</span><div className="ov-meter large"><i style={{ width: `${reserve}%` }} /></div></div><div className="ov-energy-list"><div><b>HEAVY BRAKING</b><span>RECOVERY ZONES</span><strong>3</strong></div><div><b>FULL THROTTLE</b><span>DEPLOYMENT ZONES</span><strong>5</strong></div><div><b>OVERTAKE MODE</b><span>SIMULATED BUDGET</span><strong>0.5 MJ</strong></div></div></section><section className="ov-panel ov-evidence"><div className="ov-panel-head"><span>MODEL EVIDENCE</span><b>TRACEABLE</b></div><div className="ov-evidence-item"><i>01</i><div><b>Braking intensity</b><p>Turn 14 braking creates a recovery opportunity before the straight.</p></div><strong>+0.8 MJ</strong></div><div className="ov-evidence-item"><i>02</i><div><b>Throttle demand</b><p>High throttle through the straight makes an attack energy-intensive.</p></div><strong>-2.4 MJ</strong></div><div className="ov-evidence-item"><i>03</i><div><b>Future opportunity</b><p>Reserve remains valuable for the final sector decision.</p></div><strong>HIGH</strong></div></section></div>}
      {tab === 'OVERTAKE' && <div className="ov-overtake-layout"><section className="ov-panel ov-overtake-hero"><div className="ov-panel-head"><span>OVERTAKE WINDOW</span><DataBadge tone="derived">DERIVED SCORE</DataBadge></div><strong>{feasibility}%</strong><p>FEASIBILITY SCORE</p><div className="ov-meter large"><i style={{ width: `${feasibility}%` }} /></div><div className="ov-risk"><span>RISK LEVEL</span><b className={feasibility > 70 ? 'safe' : 'watch'}>{feasibility > 70 ? 'CONTROLLED' : 'WATCH'}</b></div></section><section className="ov-panel ov-factor-panel"><div className="ov-panel-head"><span>WHAT IS DRIVING THE SCORE?</span><b>EXPLAINABLE</b></div>{[['Gap to car ahead', `${gap.toFixed(2)} sec`, 'positive'],['Closing rate', '+14.2 km/h', 'positive'],['DRS availability', drs ? 'OPEN' : 'CLOSED', drs ? 'positive' : 'negative'],['Energy cost', strategy === 'ATTACK' ? 'HIGH' : 'MEDIUM', 'negative'],['Tyre advantage', '+4 laps fresher', 'positive']].map(([label, value, tone]) => <div className="ov-factor" key={label}><span>{label}</span><b className={tone}>{value}</b><i style={{ width: tone === 'positive' ? '78%' : '42%' }} /></div>)}</section></div>}
      {tab === 'LEGENDS' && <div className="ov-legend-grid"><section className="ov-panel"><div className="ov-panel-head"><span>DATA PROVENANCE</span><b>READ THIS FIRST</b></div><div className="ov-legend-item"><DataBadge tone="real">REAL</DataBadge><p>Directly loaded from the cached historical telemetry scenario.</p></div><div className="ov-legend-item"><DataBadge tone="derived">DERIVED</DataBadge><p>Calculated from real telemetry, such as closing rate or braking intensity.</p></div><div className="ov-legend-item"><DataBadge tone="simulated">SIMULATED</DataBadge><p>Generated by the energy model. It is not private team battery data.</p></div></section><section className="ov-panel"><div className="ov-panel-head"><span>SCENARIO NOTES</span><b>LIMITATIONS</b></div><p className="ov-notes">This first demo uses one cached race scenario so the flow stays fast and reproducible. Overtake labels and energy outputs should be validated against more races before model training.</p><p className="ov-notes">Move the scrubber to inspect another moment in the lap. Every chart, metric and recommendation follows the selected focus point.</p></section></div>}
      <div className="ov-scrubber"><div><span>LAP DISTANCE</span><b>{Math.round(focus / 47 * 5412).toLocaleString()} m</b><em> / 5,412 m</em></div><input type="range" min="0" max="47" value={focus} onChange={(e) => setFocus(Number(e.target.value))} /><div className="ov-scrub-stops"><span>GRID EXIT</span><span>DRS ZONE</span><span>OVERTAKE POINT</span><span>FINISH</span></div><button className="ov-play" onClick={() => setFocus((focus + 1) % 48)}>▶ STEP</button></div>
    </section>
    <footer className="ov-footer"><span>OVERVOLT / STRATEGY INTELLIGENCE</span><span>REAL TELEMETRY · DERIVED FEATURES · MODELED ENERGY</span></footer>
  </main>
}
